/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DetailSection: typeof import('./src/components/detail/detail-section.vue')['default']
    Loading: typeof import('./src/components/loading/loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchbar: typeof import('./src/components/searchbar/searchbar.vue')['default']
    Tabbar: typeof import('./src/components/tabbar/Tabbar.vue')['default']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanDialog: typeof import('vant/es')['Dialog']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTreeSelect: typeof import('vant/es')['TreeSelect']
    VantTabBar: typeof import('./src/components/tabbar/VantTabBar.vue')['default']
  }
}
